"""DB update

Revision ID: 080b7937740b
Revises: 4640a6467a55
Create Date: 2023-01-26 20:49:23.092749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils.types import TSVectorType

# revision identifiers, used by Alembic.
revision = '080b7937740b'
down_revision = '4640a6467a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_tasks',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('app_title', sa.String(length=32), nullable=True),
    sa.Column('app_author', sa.String(length=32), nullable=True),
    sa.Column('git_hash', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('requests_search',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('query', sa.String(length=100), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('response_total', sa.Integer(), nullable=True),
    sa.Column('num_items', sa.Integer(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_commit', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('search_vector', TSVectorType(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('search_vector')
        batch_op.drop_column('last_commit')

    op.drop_table('requests_search')
    op.drop_table('build_tasks')
    # ### end Alembic commands ###
