"""Initial migration.

Revision ID: 4640a6467a55
Revises: 
Create Date: 2023-01-26 18:59:30.644373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4640a6467a55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('search_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repo_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fam_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('title', 'author')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    # ### end Alembic commands ###
