"""Initial migration.

Revision ID: 8680342bd767
Revises: 
Create Date: 2023-01-26 18:51:28.110872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8680342bd767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_tasks')
    op.drop_table('requests_search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_search',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"requests_search_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_items', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='requests_search_pkey')
    )
    op.create_table('build_tasks',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"build_tasks_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('app_title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('app_author', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('git_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='build_tasks_pkey')
    )
    # ### end Alembic commands ###
